# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'switchWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_swWindow(object):
    def setupUi(self, swWindow):
        swWindow.setObjectName("swWindow")
        swWindow.resize(647, 897)
        self.port1Msg = QtWidgets.QTextEdit(swWindow)
        self.port1Msg.setGeometry(QtCore.QRect(0, 120, 321, 231))
        self.port1Msg.setObjectName("port1Msg")
        self.port2Msg = QtWidgets.QTextEdit(swWindow)
        self.port2Msg.setGeometry(QtCore.QRect(330, 120, 321, 231))
        self.port2Msg.setObjectName("port2Msg")
        self.port3Msg = QtWidgets.QTextEdit(swWindow)
        self.port3Msg.setGeometry(QtCore.QRect(0, 400, 321, 231))
        self.port3Msg.setObjectName("port3Msg")
        self.port4Msg = QtWidgets.QTextEdit(swWindow)
        self.port4Msg.setGeometry(QtCore.QRect(330, 400, 321, 231))
        self.port4Msg.setObjectName("port4Msg")
        self.label = QtWidgets.QLabel(swWindow)
        self.label.setGeometry(QtCore.QRect(120, 94, 72, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(swWindow)
        self.label_2.setGeometry(QtCore.QRect(460, 90, 72, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(swWindow)
        self.label_3.setGeometry(QtCore.QRect(120, 370, 72, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(swWindow)
        self.label_4.setGeometry(QtCore.QRect(450, 370, 72, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.title = QtWidgets.QLabel(swWindow)
        self.title.setGeometry(QtCore.QRect(270, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.background = QtWidgets.QTextEdit(swWindow)
        self.background.setGeometry(QtCore.QRect(0, 0, 651, 901))
        self.background.setObjectName("background")
        self.active_port = QtWidgets.QLabel(swWindow)
        self.active_port.setGeometry(QtCore.QRect(340, 50, 131, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.active_port.setFont(font)
        self.active_port.setObjectName("active_port")
        self.label_6 = QtWidgets.QLabel(swWindow)
        self.label_6.setGeometry(QtCore.QRect(260, 650, 151, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.transmitCtrl = QtWidgets.QLabel(swWindow)
        self.transmitCtrl.setGeometry(QtCore.QRect(200, 50, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.transmitCtrl.setFont(font)
        self.transmitCtrl.setObjectName("transmitCtrl")
        self.addrTable = QtWidgets.QTableWidget(swWindow)
        self.addrTable.setGeometry(QtCore.QRect(30, 680, 601, 221))
        self.addrTable.setObjectName("addrTable")
        self.addrTable.setColumnCount(0)
        self.addrTable.setRowCount(0)
        self.background.raise_()
        self.port1Msg.raise_()
        self.port2Msg.raise_()
        self.port3Msg.raise_()
        self.port4Msg.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.title.raise_()
        self.active_port.raise_()
        self.label_6.raise_()
        self.transmitCtrl.raise_()
        self.addrTable.raise_()

        self.retranslateUi(swWindow)
        QtCore.QMetaObject.connectSlotsByName(swWindow)

    def retranslateUi(self, swWindow):
        _translate = QtCore.QCoreApplication.translate
        swWindow.setWindowTitle(_translate("swWindow", "Form"))
        self.label.setText(_translate("swWindow", "端口1"))
        self.label_2.setText(_translate("swWindow", "端口2"))
        self.label_3.setText(_translate("swWindow", "端口3"))
        self.label_4.setText(_translate("swWindow", "端口4"))
        self.title.setText(_translate("swWindow", "交换机1"))
        self.active_port.setText(_translate("swWindow", "活跃端口："))
        self.label_6.setText(_translate("swWindow", "MAC地址表"))
        self.transmitCtrl.setText(_translate("swWindow", "转发方式："))
